### ISSUE TITLE
Dúvidas quanto aos dados

### ISSUE THREAD

**Issue by luiseduardobr1** [integrasus/api-covid-ce#2]
Estou com algumas dúvidas quanto a base de dados, se puder esclarecer:

1) Observei que em muitos casos "dataNotificacao" ocorre muito tempo depois de "dataResultadoExame". Eu entendi por "dataNotificacao" a data de notificação no sistema público do exame realizado, mas por que só muitos dias depois ele é alterado ? Ou ele seria o dia da notificação do caso confirmado? Neste último caso não faria sentido.

2) Como filtrar todos os casos hospitalizados ? Seria pelo idSivep ? Então, quem não tem idSivep não foi hospitalizado ?

3) Quando eu tento ver os casos confirmados eu tiro "codigoPaciente" duplicados, contudo se mantenho somente o último (dos duplicados) tem 2031 casos confirmados de COVID19 positivos enquanto se mantenho somente o primeiro (dos duplicados) tem 2051 casos confirmados de COVID19. A título de análise observei que o codigoPaciente = "7c94738d0a878e0c8244f57f9f41fdf7" tem três incidências sendo duas positivas e uma negativa. Sem falar que tem incidência desse codigo que tem algumas informações que as outras não tem. E aí como avaliar nessa situação ?

![image](https://user-images.githubusercontent.com/56649205/79290677-2b554900-7ea3-11ea-8ba2-4deb93528503.png)

**Comment by rafaelmff** [comment]
Olá Luis Eduardo.

Meu nome é Rafael, sou parte da equipe do Integrasus. Respondo aqui suas perguntas:

1) Data de notificação é a data que o paciente foi registrado em um dos sistemas (Redcap, Esus, Sivep) como caso suspeito. Ocorre que alguns pacientes foram diretamente ao laboratório, por contra própria, para fazer o exame, e apenas posteriormente os municípios foram informados sobre o resultado do exame da pessoa e então fez a notificação. Por isso ocorre, em alguns casos, da data de notificação ser posterior ao resultado do exame. 

2) Sim, o filtro dos casos hospitalizados é obtido pelo Id Sivep. Os que possuem um ID nesse campo foram hospitalizados.

3) A regra que utilizamos hoje é que se o paciente teve algum resultado que deu resultado positivo, então ele será considerado positivo.

Espero ter respondido suas perguntas. Se tiver mais, informa aqui.
