### ISSUE TITLE
Reproduzir o número de confirmados no site

### ISSUE THREAD

**Issue by luiseduardobr1** [integrasus/api-covid-ce#3]
Estou tentando reproduzir o mesmo valor apresentado no site do integrasus para o número de casos confirmados de COVID-19 no estado. Já li o [Dicionário de dados](https://drive.google.com/file/d/1DUwST2zcXUnCJmJauiM5zmpSVWqLiAYI/view), mas o valor que encontro ainda está um pouco diferente do portal. 

O número de municípios bate, porém percebo que os casos de "Fortaleza" e "Sem informação" dão um valor diferente do esperado. Para os casos confirmados, utilizei os seguintes critérios em ordem (em python):

* Filtra os exames com resultado "Positivo"
```Python
    analise = analise[(analise['resultadoFinalExame']) == 'Positivo']
```
* Dos que sobraram, filtrar os que "estadoPaciente" seja igual a "CE" ou null. 
```Python
    analise = analise[(analise['estadoPaciente']=='CE') | (analise['estadoPaciente'].isnull())]
```
* Criei uma coluna "dataCovalesce" que tem o valor em ordem de prioridade: "dataInicioSintomas", se for null, então, coloca dataSolicitacaoExame, se for null, então, coloca dataResultadoExame, se for null, então, coloca dataNotificacao. Fiz essa coluna, porém todas as vezes que tento filtrar algo com ela dá bem diferente do resultado esperado. Mesmo deixando somente dataInicioSintomas, dataSolicitacaoExame e dataResultadoExame. Então, deixei essa coluna, mas não filtrei nada com ela por ora. 
```Python
    analise['dataCovalesce'] = (analise['dataInicioSintomas'].combine_first(analise['dataSolicitacaoExame']).combine_first(analise['dataResultadoExame']
                                                                                                                          .combine_first(analise['dataNotificacao'])))
```

* Como há muitos "codigoPaciente" repetidos (e com valores de "municipioPaciente" diferentes) tentei apagar as linhas com "codigoPaciente" e "municipioPaciente" idênticos (mantendo apenas a primeira ocorrência), organizando em ordem alfabética por município para que os valores "null" ficassem no final da base de dados. 
```Python
analise = analise.sort_values('municipioPaciente', ascending=True).drop_duplicates(subset=['codigoPaciente','municipioPaciente'], keep='first')
```

* Com o trecho de código anterior, eu consegui excluir todas as linhas que tinham codigoPaciente e municipioPaciente idênticos. Só que restam os casos em que há o mesmo codigoPaciente, mas com municipioPaciente diferentes. Como os municipioPaciente com valor null ficaram no final do dataframe, eu exclui as linhas com codigoPaciente repetido e mantendo a primeira ocorrencia (que teria o valor do municipioPaciente).
```Python
analise = analise.drop_duplicates(subset=['codigoPaciente'], keep='first')
```

Após isso, ao meu ver, eu teria o número de casos confirmados únicos no dataframe "analise". Para confirmar, utilizei (anteriormente de aplicar esse código acima) uma única linha de código que resume todo esse meu procedimento pegando os codigoPaciente únicos e dando o valor. 
```Python
print(analise.codigoPaciente.nunique())
```

Em ambos os códigos, executando às 21/04 11:59h dá um valor de 3507 casos confirmados, enquanto no integrasus está 3484. Notei que a diferença está nos municípios de Fortaleza e sem informação:
**meu código:**
```Python
              Municípios  Valores
0              FORTALEZA     2846
1         Sem informação       99
2                CAUCAIA       89
3              MARACANAU       79
4                AQUIRAZ       38
```
**integraSUS:**
```Python
FORTALEZA | 2.840
CAUCAIA | 89
Sem informação | 82
MARACANAU | 79
AQUIRAZ | 38
```

Desse modo, gostaria de uma ajuda para conseguir reproduzir o número de confirmados no integraSUS a título de análise. O código completo está no [link](https://github.com/luiseduardobr1/covid19-Ceara/blob/master/algoritmos/API-integrasus.py).

**Comment by rafaelmff** [comment]
Olá Luis Eduardo.

Sua consulta está sendo correta. Antes de tirar suas dúvidas, peço que aguarde um pouco. Vamos subir uma versão nova do dicionário de dados e do tratamento dos dados que poderão sanar diversas das suas dúvidas. 

Vou deixar este chamado aberto até que tenhamos sanado sua dúvida.

**Comment by luiseduardobr1** [comment]
Estarei no aguardo Rafael, obrigado!

**Comment by rafaelmff** [comment]
Olá Luis Eduardo. Com as mudanças feitas em nossa base de dados, acredito que suas consultas devem apresentar valores idênticos ao integraus. Por favor, me diz você ainda há alguma discrepância.

**Comment by luiseduardobr1** [comment]
Obrigado pela resposta rafael
