### ISSUE TITLE
Reproduzir o número de exames realizados

### ISSUE THREAD

**Issue by luiseduardobr1** [integrasus/api-covid-ce#4]
De forma análoga ao meu [issue anterior](https://github.com/integrasus/api-covid-ce/issues/3), estou tentando reproduzir o número de exames realizados de acordo com o apresentado no portal do integrasus para COVID-19. Já li o dicionário de dados disponibilizado, mas mesmo assim estou com dificuldade para obter o mesmo valor. 

Minha lógica para os exames realizados foi:
1) Filtrar apenas os casos que resultadoFinalExame não seja null
2) Criar uma coluna "dataCovalesce" que pega o valor de dataSolicitacaoExame e caso seja null pega dataResultadoExame. 
3) Depois tiro as linhas duplicadas com idênticos codigoPaciente+municipioPaciente. 

Eu fiz outras tentativas mudando a lógica, mas ainda assim não consigo bater de jeito nenhum o valor apresentado. Poderiam me ajudar a organizar melhor o código para que consiga obter o valor ?

Segue o código em python desse trecho completo:

```Python
def exames_realizados(analise):
    # Tira os NaN dos resultados
    analise = analise[analise['resultadoFinalExame'].isnull()==False]
    analise['dataCovalesce'] = (analise['dataSolicitacaoExame'].combine_first(analise['dataResultadoExame']))

    #analise = analise[(analise['dataCovalesce'].isnull()==False) | ((analise['municipioPaciente'].isnull()==False))]
    
    #analise = analise.sort_values('municipioPaciente', ascending=True).drop_duplicates(subset=['codigoPaciente', 'resultadoFinalExame', 'dataCovalesce', 'municipioPaciente', 'dataInicioSintomas','dataNotificacao'], keep='first')
    analise = analise.sort_values('municipioPaciente', ascending=True).drop_duplicates(subset=['codigoPaciente', 'municipioPaciente'])
                                                                                              
    
    
    
    print('Total de exames realizados: '+ str(len(analise)))
    return(analise)
```

**Comment by rafaelmff** [comment]
Olá Luis Eduardo. Com as mudanças feitas em nossa base de dados, acredito que suas consultas devem apresentar valores idênticos ao integraus. Por favor, me diz você ainda há alguma discrepância.

**Comment by luiseduardobr1** [comment]
Obrigado pelo retorno, Rafael.
