### ISSUE TITLE
Obter número de hospitalizações

### ISSUE THREAD

**Issue by luiseduardobr1** [integrasus/api-covid-ce#5]
Estava pensando em tentar extrair da base o número de pacientes hospitalizados com COVID-19 no estado. Com isso, pensei em filtrar pela coluna "idSivep" uma vez que de acordo com esse [issue](https://github.com/integrasus/api-covid-ce/issues/2) se tiver valor nessa coluna, então, houve hospitalização. 

No entanto, eu observei que, se tento filtrar por "idSivep", aparecem muitos casos de pacientes que tem valor nessa coluna, mas que ao mesmo tempo têm, na coluna "resultadoFinalExame", resultado negativo e inconclusivo (além de null, positivo). 

Então, como fica a questão da análise das hospitalizações decorrentes de COVID-19 ?

**Comment by rafaelmff** [comment]
Os pacientes com IdSivep foram internados por terem sido diagnosticadas com síndrome respiratória aguda grave (SRAG). Dentre os pacientes internados com SRAG, alguns serão diagnosticados com COVID, outros não. 
Se você quiser obter apenas as internações decorrentes de covid, será preciso pegar os casos com IdSivep e com resultado de exame positivo.

**Comment by luiseduardobr1** [comment]
> Os pacientes com IdSivep foram internados por terem sido diagnosticadas com síndrome respiratória aguda grave (SRAG). Dentre os pacientes internados com SRAG, alguns serão diagnosticados com COVID, outros não.
> Se você quiser obter apenas as internações decorrentes de covid, será preciso pegar os casos com IdSivep e com resultado de exame positivo.

Os pacientes internados em hospitais privados também têm idSivep ou se restringe aos hospitais públicos?

**Comment by rafaelmff** [comment]
Olá, Luis Eduardo. 

Sim, os pacientes internados em hospitais privados também possuem uma Id Sivep. Segundo portaria do ministério da saúde, todos os pacientes com Síndrome Respiratória Aguda Grave (SRAG) devem ser informados no Sivep, seja em instituições públicas ou privadas.

**Comment by luiseduardobr1** [comment]
Issue esclarecido. Obrigado Rafael.
